run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - godox
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gomnd
    - lll
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl
    - depguard
    - testpackage
    - paralleltest
    - funlen
    - gocognit
    - cyclop
    - gocyclo

linters-settings:
  goimports:
    local-prefixes: github.com/voideng/eidolon-engine
  
  govet:
    check-shadowing: true
    enable-all: true
  
  revive:
    severity: warning
    confidence: 0.8
  
  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    
    - linters:
        - lll
      source: "^//go:generate "

  max-issues-per-linter: 0
  max-same-issues: 0