version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - mkdir -p python/lib/python3.12/site-packages
      - pip install -r requirements/lambda-requirements.txt -t python/lib/python3.12/site-packages/
      - find python -type d -name '__pycache__' -prune -exec rm -rf {} +
      - find python -type f -name '*.pyc' -delete
      - zip -r lambda-layer.zip python/

  post_build:
    commands:
      - aws s3 cp lambda-layer.zip "s3://$S3_BUCKET/lambda-layer/lambda-layer.zip"
