version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies for Lambda layer

  build:
    commands:
      - echo Building Lambda layer
      - mkdir -p python/lib/python3.11/site-packages
      - pip install -r requirements/lambda-requirements.txt -t python/lib/python3.11/site-packages/
      - zip -r lambda-layer.zip python/

artifacts:
  files:
    - lambda-layer.zip
  name: lambda-layer
