// Mocks generated by Mockito 5.4.6 from annotations
// in eidolon_incremental/test/integration/game_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:amazon_cognito_identity_dart_2/cognito.dart' as _i3;
import 'package:eidolon_incremental/models/character.dart' as _i7;
import 'package:eidolon_incremental/models/segment_outcome.dart' as _i2;
import 'package:eidolon_incremental/services/api_service.dart' as _i4;
import 'package:eidolon_incremental/services/auth_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSegmentOutcome_0 extends _i1.SmartFake
    implements _i2.SegmentOutcome {
  _FakeSegmentOutcome_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCognitoUserPool_1 extends _i1.SmartFake
    implements _i3.CognitoUserPool {
  _FakeCognitoUserPool_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCognitoUserPoolData_2 extends _i1.SmartFake
    implements _i3.CognitoUserPoolData {
  _FakeCognitoUserPoolData_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCognitoUser_3 extends _i1.SmartFake implements _i3.CognitoUser {
  _FakeCognitoUser_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i6.Future<Map<String, dynamic>> addCharacter({
    required String? name,
    required String? archetype,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addCharacter, [], {
              #name: name,
              #archetype: archetype,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> deleteCharacter(String? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCharacter, [characterId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i7.Character?> getCharacterById(String? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#getCharacterById, [characterId]),
            returnValue: _i6.Future<_i7.Character?>.value(),
          )
          as _i6.Future<_i7.Character?>);

  @override
  _i6.Future<List<_i4.CharacterInfo>> listCharacters() =>
      (super.noSuchMethod(
            Invocation.method(#listCharacters, []),
            returnValue: _i6.Future<List<_i4.CharacterInfo>>.value(
              <_i4.CharacterInfo>[],
            ),
          )
          as _i6.Future<List<_i4.CharacterInfo>>);

  @override
  _i6.Future<Map<String, dynamic>> startStory({
    required String? characterId,
    required String? storyId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startStory, [], {
              #characterId: characterId,
              #storyId: storyId,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> submitDecision({
    required String? characterId,
    required String? decision,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitDecision, [], {
              #characterId: characterId,
              #decision: decision,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getSegmentOutcome({
    required String? characterId,
    required String? segmentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSegmentOutcome, [], {
              #characterId: characterId,
              #segmentId: segmentId,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i2.SegmentOutcome> concludeSegment({
    required String? segmentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#concludeSegment, [], {#segmentId: segmentId}),
            returnValue: _i6.Future<_i2.SegmentOutcome>.value(
              _FakeSegmentOutcome_0(
                this,
                Invocation.method(#concludeSegment, [], {
                  #segmentId: segmentId,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.SegmentOutcome>);

  @override
  _i6.Future<Map<String, dynamic>> abandonStory(String? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#abandonStory, [characterId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> rest(String? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#rest, [characterId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i4.ArchetypeInfo>> getArchetypes() =>
      (super.noSuchMethod(
            Invocation.method(#getArchetypes, []),
            returnValue: _i6.Future<List<_i4.ArchetypeInfo>>.value(
              <_i4.ArchetypeInfo>[],
            ),
          )
          as _i6.Future<List<_i4.ArchetypeInfo>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getSegmentHistory({
    required String? characterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSegmentHistory, [], {
              #characterId: characterId,
            }),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>> getSegmentStatus({
    required String? characterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSegmentStatus, [], {
              #characterId: characterId,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CognitoUserPool get userPool =>
      (super.noSuchMethod(
            Invocation.getter(#userPool),
            returnValue: _FakeCognitoUserPool_1(
              this,
              Invocation.getter(#userPool),
            ),
          )
          as _i3.CognitoUserPool);

  @override
  _i6.Future<String?> get currentUserEmail =>
      (super.noSuchMethod(
            Invocation.getter(#currentUserEmail),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  set userPool(_i3.CognitoUserPool? _userPool) => super.noSuchMethod(
    Invocation.setter(#userPool, _userPool),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.CognitoUserPoolData> signUp(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [email, password]),
            returnValue: _i6.Future<_i3.CognitoUserPoolData>.value(
              _FakeCognitoUserPoolData_2(
                this,
                Invocation.method(#signUp, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i3.CognitoUserPoolData>);

  @override
  _i6.Future<bool> confirmRegistration(String? email, String? code) =>
      (super.noSuchMethod(
            Invocation.method(#confirmRegistration, [email, code]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i3.CognitoUser> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i6.Future<_i3.CognitoUser>.value(
              _FakeCognitoUser_3(
                this,
                Invocation.method(#signIn, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i3.CognitoUser>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getIdToken() =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> resendConfirmationCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendConfirmationCode, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> confirmPassword(
    String? email,
    String? code,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPassword, [email, code, newPassword]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUser() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
