// Mocks generated by Mockito 5.4.6 from annotations
// in eidolon_incremental/test/screens/game_screen_polling_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:eidolon_incremental/models/character.dart' as _i5;
import 'package:eidolon_incremental/services/api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i2.Future<Map<String, dynamic>> addCharacter({
    required String? name,
    required String? archetype,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addCharacter, [], {
              #name: name,
              #archetype: archetype,
            }),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<Map<String, dynamic>> deleteCharacter(String? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCharacter, [characterId]),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<_i5.Character?> getCharacterById(String? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#getCharacterById, [characterId]),
            returnValue: _i2.Future<_i5.Character?>.value(),
            returnValueForMissingStub: _i2.Future<_i5.Character?>.value(),
          )
          as _i2.Future<_i5.Character?>);

  @override
  _i2.Future<List<_i3.CharacterInfo>> listCharacters() =>
      (super.noSuchMethod(
            Invocation.method(#listCharacters, []),
            returnValue: _i2.Future<List<_i3.CharacterInfo>>.value(
              <_i3.CharacterInfo>[],
            ),
            returnValueForMissingStub:
                _i2.Future<List<_i3.CharacterInfo>>.value(
                  <_i3.CharacterInfo>[],
                ),
          )
          as _i2.Future<List<_i3.CharacterInfo>>);

  @override
  _i2.Future<Map<String, dynamic>> startStory({
    required String? characterId,
    required String? storyId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startStory, [], {
              #characterId: characterId,
              #storyId: storyId,
            }),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<Map<String, dynamic>> submitDecision({
    required String? characterId,
    required String? decision,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitDecision, [], {
              #characterId: characterId,
              #decision: decision,
            }),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<Map<String, dynamic>> abandonStory(String? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#abandonStory, [characterId]),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<Map<String, dynamic>> rest(String? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#rest, [characterId]),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<List<_i3.ArchetypeInfo>> getArchetypes() =>
      (super.noSuchMethod(
            Invocation.method(#getArchetypes, []),
            returnValue: _i2.Future<List<_i3.ArchetypeInfo>>.value(
              <_i3.ArchetypeInfo>[],
            ),
            returnValueForMissingStub:
                _i2.Future<List<_i3.ArchetypeInfo>>.value(
                  <_i3.ArchetypeInfo>[],
                ),
          )
          as _i2.Future<List<_i3.ArchetypeInfo>>);

  @override
  _i2.Future<List<Map<String, dynamic>>> getSegmentHistory({
    required String? characterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSegmentHistory, [], {
              #characterId: characterId,
            }),
            returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i2.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Future<Map<String, dynamic>> getSegmentStatus({
    required String? characterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSegmentStatus, [], {
              #characterId: characterId,
            }),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<Map<String, String>> getHeaders() =>
      (super.noSuchMethod(
            Invocation.method(#getHeaders, []),
            returnValue: _i2.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i2.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i2.Future<Map<String, String>>);

  @override
  _i2.Future<T> executeRequest<T>({
    required String? method,
    required String? endpoint,
    Map<String, dynamic>? body,
    Map<String, String>? queryParams,
    T Function(Map<String, dynamic>)? parser,
    bool? returnRawResponse = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeRequest, [], {
              #method: method,
              #endpoint: endpoint,
              #body: body,
              #queryParams: queryParams,
              #parser: parser,
              #returnRawResponse: returnRawResponse,
            }),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeRequest, [], {
                      #method: method,
                      #endpoint: endpoint,
                      #body: body,
                      #queryParams: queryParams,
                      #parser: parser,
                      #returnRawResponse: returnRawResponse,
                    }),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#executeRequest, [], {
                    #method: method,
                    #endpoint: endpoint,
                    #body: body,
                    #queryParams: queryParams,
                    #parser: parser,
                    #returnRawResponse: returnRawResponse,
                  }),
                ),
            returnValueForMissingStub:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeRequest, [], {
                      #method: method,
                      #endpoint: endpoint,
                      #body: body,
                      #queryParams: queryParams,
                      #parser: parser,
                      #returnRawResponse: returnRawResponse,
                    }),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#executeRequest, [], {
                    #method: method,
                    #endpoint: endpoint,
                    #body: body,
                    #queryParams: queryParams,
                    #parser: parser,
                    #returnRawResponse: returnRawResponse,
                  }),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> get<T>(
    String? endpoint, {
    Map<String, String>? queryParams,
    T Function(Map<String, dynamic>)? parser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {#queryParams: queryParams, #parser: parser},
            ),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #get,
                      [endpoint],
                      {#queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #get,
                    [endpoint],
                    {#queryParams: queryParams, #parser: parser},
                  ),
                ),
            returnValueForMissingStub:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #get,
                      [endpoint],
                      {#queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #get,
                    [endpoint],
                    {#queryParams: queryParams, #parser: parser},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> post<T>(
    String? endpoint, {
    Map<String, dynamic>? body,
    Map<String, String>? queryParams,
    T Function(Map<String, dynamic>)? parser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {#body: body, #queryParams: queryParams, #parser: parser},
            ),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #post,
                      [endpoint],
                      {#body: body, #queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #post,
                    [endpoint],
                    {#body: body, #queryParams: queryParams, #parser: parser},
                  ),
                ),
            returnValueForMissingStub:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #post,
                      [endpoint],
                      {#body: body, #queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #post,
                    [endpoint],
                    {#body: body, #queryParams: queryParams, #parser: parser},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> put<T>(
    String? endpoint, {
    Map<String, dynamic>? body,
    Map<String, String>? queryParams,
    T Function(Map<String, dynamic>)? parser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {#body: body, #queryParams: queryParams, #parser: parser},
            ),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #put,
                      [endpoint],
                      {#body: body, #queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #put,
                    [endpoint],
                    {#body: body, #queryParams: queryParams, #parser: parser},
                  ),
                ),
            returnValueForMissingStub:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #put,
                      [endpoint],
                      {#body: body, #queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #put,
                    [endpoint],
                    {#body: body, #queryParams: queryParams, #parser: parser},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> delete<T>(
    String? endpoint, {
    Map<String, String>? queryParams,
    T Function(Map<String, dynamic>)? parser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {#queryParams: queryParams, #parser: parser},
            ),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #delete,
                      [endpoint],
                      {#queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #delete,
                    [endpoint],
                    {#queryParams: queryParams, #parser: parser},
                  ),
                ),
            returnValueForMissingStub:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #delete,
                      [endpoint],
                      {#queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #delete,
                    [endpoint],
                    {#queryParams: queryParams, #parser: parser},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> patch<T>(
    String? endpoint, {
    Map<String, dynamic>? body,
    Map<String, String>? queryParams,
    T Function(Map<String, dynamic>)? parser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint],
              {#body: body, #queryParams: queryParams, #parser: parser},
            ),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #patch,
                      [endpoint],
                      {#body: body, #queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #patch,
                    [endpoint],
                    {#body: body, #queryParams: queryParams, #parser: parser},
                  ),
                ),
            returnValueForMissingStub:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #patch,
                      [endpoint],
                      {#body: body, #queryParams: queryParams, #parser: parser},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #patch,
                    [endpoint],
                    {#body: body, #queryParams: queryParams, #parser: parser},
                  ),
                ),
          )
          as _i2.Future<T>);
}
